[directory]
truncation_length = 6
truncate_to_repo = true
style = "bold cyan"
disabled = false

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 20
style = "bold orange"

[git_branch]
symbol = "🌱 "

[git_commit]
commit_hash_length = 8

[git_state]
cherry_pick = "CHERRY PICKING"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bold yellow"

[line_break]
disabled = false

[nodejs]
symbol = "⬢ "
style = "bold green"
disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false

[gcloud]
disabled=true

[python]
# Only use the `python3` binary to get the version.
python_binary = "python3"
